### ISSUE TITLE
Release 3.9.0

### ISSUE THREAD

**Issue by dcousens** [fukuchi/libqrencode#104]
Your README lists `3.9.0`,  but https://fukuchi.org/works/qrencode/ is only `3.4.4`,  matching the https://github.com/fukuchi/libqrencode/releases.

Is there any reason >`3.4.4` hasn't been released yet?
Great library!

**Comment by yaleimeng** [comment]
Glad to see this lib updating...   Thanks to the author and contributors!

**Comment by fukuchi** [comment]
Hi all,

3.9..0 is not released yet. The reason behind this delay is #89. I wanted to release 4.0.0 that fixes the issue but it includes a huge change of API, I need time to fix and test the problem.

If you need an official release of 3.9.0, I think I can release 3.9.0 without #89, then release 4.0.0 fixes #89.

**Comment by dcousens** [comment]
@fukuchi do you want help with #89?

**Comment by fukuchi** [comment]
@dcousens Thank you for your offer. PR is always welcome.

By the way, I have changed the release policy. Soon I'll release the 4.0.0 without #89, because I deeply checked the API definitions and found that #89 will not introduce any API changes. Sorry for my last comment.

Soon after I release the 4.0.0, let us solve the issue of #89.

**Comment by dcousens** [comment]
@fukuchi look forward to it!

**Comment by dcousens** [comment]
@fukuchi is there any documentation as to why the major bump to `4.0.0`?  What was backwards incompatible?

**Comment by fukuchi** [comment]
@dcousens Good question. As you noted, the API is not changed from 3.4.4, but the implementation of the library has been largely changed. One of the biggest change is the elimination of data caching (see b650d72). That's the reason of major bump.

**Comment by fukuchi** [comment]
Hi folks,

Version 4.0.0-RC1 is now available. 6af0665b39
