### ISSUE TITLE
Should we use a testing framework?

### ISSUE THREAD

**Issue by fukuchi** [fukuchi/libqrencode#106]
Currently, unit tests of libqrencode are written manually. It works well now, but not good enough for further development.

After a quick survey, I found two possible testing framework for our library written in C:

* [CUnit](http://cunit.sourceforge.net/)
* [GoogleTest](https://github.com/google/googletest)

Pros of using testing frameworks:

* easy to maintain. (probably)
* familiar for developers.
* better visualization of the results

Cons:

* another dependency
* hard to maintain. (dependency check, cross-platform portability)

Your comments are welcome.

**Comment by dcousens** [comment]
IMHO,  no.
The only pro that doesn't hold true for *not* using a framework might be "better visualization of the results".
This can be improved upon indepedently, and does not require a *framework* as such.

>  but not good enough for further development.
How so?

**Comment by fukuchi** [comment]
> How so?

It becomes difficult for me to write a new test case, especially the cases of integratio tests. For example, now I'm writing some test script for qrencode command. I this case, the test cases have to check the output (including error messages) from the command, and writing asset functions of them without any assists from the frameworks is bothering and difficult.

**Comment by dcousens** [comment]
I don't think CUnit,  or any in-code testing framework is going to assist in testing the resultant binary.
You need a bash/shell testing framework for that,  probably.

**Comment by fukuchi** [comment]
Thank you @dcousens , you're right. Both CUnit and GoogleTest do not provide CLI testing framework.

This article recommends Bat, Expect, Tush and Empty. I'll try them later.

https://spin.atomicobject.com/2016/01/11/command-line-interface-testing-tools/

**Comment by fukuchi** [comment]
I have just introduced the Test Anything Protocol (TAP) for the test programs. Now you can run all test programs by typing 'make check' and the result is visualized nicely. The test cases are written without any testing frameworks not yet, but the current implementation seems not bad.
