### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by SanderKo** [fukuchi/libqrencode#107]
When i try to install and type in the terminal ./configure
I get a error saying: Task not found.
Even though there is a file in the folder called configure.ac
Am I doing something wrong?

**Comment by fukuchi** [comment]
Hi,

If you download the source tree from github, you have to run ./autogen.sh at first to generate configure script from configure.ac.

**Comment by SanderKo** [comment]
Thanks for your reply. Im running the autogen file at this moment, but it's taking over half an hour and still not finished. Should it take anywhere near this long?

**Comment by SanderKo** [comment]
BTW, The long running of autogen is when i write autogen in the libqrencode-master directery (so without .sh at the end) When i write it with .sh at the end I get an error saying: Task not found. I checked iff the file is in the directtory and it clearly is. When is check this in the terminal by writing ls in the libqrencode directory i see the autogen.sh file in the list and it is writen in bold green style.

**Comment by SanderKo** [comment]
I also tried this:
~$ '/home/sander/libqrencode-master/autogen.sh'

Then got this error: 
autoheader: 'configure.ac' or 'configure.in' is required

**Comment by SanderKo** [comment]
![afbeelding](https://user-images.githubusercontent.com/32374525/31026135-7e1ed8d4-a545-11e7-81e4-5e61d3b618e2.png)

**Comment by fukuchi** [comment]
Please type "./autogen.sh" to activate the autogens.h included in the tarball.

$ cd libqrencode-master
$ ./autogen.sh

**Comment by SanderKo** [comment]
I think there was something wrong with the standard program to run the autogen.sh file. When I opened it as a text file and pasted the code into the terminal it worked, and the same worked for the config file. Got it running now. Thank you for your help
