### ISSUE TITLE
Compiling problem with LIBPNG

### ISSUE THREAD

**Issue by SEMI-K** [fukuchi/libqrencode#111]
I try to compile qrencode on Debian 8 but ./configure step give an alert about LIBPNG 
> checking for png... no
> 
> !!!!!!!!!!
> LIBPNG is required to build the utility tools. Temporarily disabled.
> !!!!!!!!!!

I've reinstall libpng (apt-get install libpng-dev ) but it doesn't work.
Any ideas ?
Thanks for helping.

**Comment by fukuchi** [comment]
Install libpng12-dev instead of libpng-dev and run ./configure again, then please let me know the result.

**Comment by SEMI-K** [comment]
Thanks for reply.
It was already done with no success...

**Comment by SEMI-K** [comment]
Here is the result of ./configure  :+1: 
`checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for pkg-config... no
checking for strdup... yes
checking for pthread_mutex_init in -lpthread... yes
checking for png... no

!!!!!!!!!!
LIBPNG is required to build the utility tools. Temporarily disabled.
!!!!!!!!!!

checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libqrencode.pc
config.status: creating tests/Makefile
config.status: creating qrencode.1
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Options used to compile and link:
  CC       = gcc
  CFLAGS   = -Wall -g -O2 -pthread
  CPPFLAGS = 
  CXX      = 
  CXXFLAGS = 
  LDFLAGS  =`

**Comment by fukuchi** [comment]
Open config.log then search ‘png’. There must be some hints why it failed to find libpng...

**Comment by SEMI-K** [comment]
Thanks for reply.
Here is the hints : 
configure:13097: checking for png
configure:13157: result: no

ac_cv_env_png_CFLAGS_set=
ac_cv_env_png_CFLAGS_value=
ac_cv_env_png_CFLAGS_value=

HAVE_PNG_FALSE=''
HAVE_PNG_TRUE='#'

png_CFLAGS=''
png_LIBS=''

#define HAVE_PNG 0
------------------------------------
For information, it's the same error with libpng with compiling qrencode 3.4.4 or installing via apt-get install qrencode.
Path : 
echo $PKG_CONFIG_PATH => /usr/local/lib/pkgconfig

I'll try to find... ありがとうございます。

**Comment by Preen** [comment]
+1

**Comment by JustCuriously** [comment]
+1 on windows with MINGW32, I have tried with ./configure --without-png but not success: 

```
./configure: line 12280: syntax error near unexpected token `png,'
./configure: line 12280: `      PKG_CHECK_MODULES(png, "libpng", AC_DEFINE([HAVE_PNG], [1], [Define to 1 if using libpng is enabled.]), AC_DEFINE([HAVE_PNG], [0]))'
```

Is there a way to give the path to the check function ?

**Comment by Preen** [comment]
Still an issue. Is there any solution for this?

**Comment by Preen** [comment]
I got it working by installing all these 
`sudo apt-get install autoconf automake autotools-dev libtool pkg-config libpng12-dev`

Dont know which one did it, but it wasnt the libpng12-dev. Because that had already been installed.

```
The following NEW packages will be installed:
  autoconf automake autotools-dev libltdl-dev libtool m4 pkg-config
0 upgraded, 7 newly installed, 0 to remove and 21 not upgraded.
```
These were the ones that were installed.
