### ISSUE TITLE
How to compile a static qrencode.exe utility

### ISSUE THREAD

**Issue by Globik** [fukuchi/libqrencode#113]
Is it possible? In order to use properly on a heroku dyno on a readonly file system. There is a problem with ln symbolic to create some libqrencode.so.4@

**Comment by Globik** [comment]
Ah I see how to. I should run like this ./configure --enable-static --enable-shared=0
And then no need any more those libqrencode.so.4 stuff...

**Comment by Globik** [comment]
By the way, what does it mean PKGS?

**Comment by fukuchi** [comment]
No idea. BTW, you can simply give '--disable-shared' for that purpose.
