### ISSUE TITLE
test_configure.sh breaks configuration

### ISSUE THREAD

**Issue by henrich** [fukuchi/libqrencode#117]
During Debian package build, test_all.sh is called after build. After test works, install files to debian package directory (i.e. qrencode-4.0.0/debian/tmp).

If we kick test_configure.sh test stage, it overwrites previous configuration options (like --prefix, package specifies --prefix=/usr but test_configure.sh overwrites it as default /usr/local).

**Comment by fukuchi** [comment]
Hi,

Thank you for the report. I didn't notice that the Debian package called test_all.sh automatically. I recommend the package manager to call test_basic.sh instead, that avoids calling test_configure.sh.

Soon I'll check the latest package and tell the managers this.

**Comment by jtojnar** [comment]
It might be nice to have `make check` run the tests as described in https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html

```patch
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -11,7 +11,7 @@
 pngPROGRAMS = create_frame_pattern create_mqr_frame_pattern
 endif
 
-noinst_PROGRAMS = test_qrinput test_bitstream test_estimatebit \
+check_PROGRAMS = test_qrinput test_bitstream test_estimatebit \
 				  test_qrspec test_rs test_qrencode prof_qrencode \
 				  test_mqrspec test_split test_monkey test_mask test_mmask \
 				  test_split_urls \
@@ -20,9 +20,11 @@
 DECODER_LIBS = libdecoder.a $(LIBICONV)
 noinst_HEADERS = common.h rscode.h
 if HAVE_LIBPTHREAD
-noinst_PROGRAMS += pthread_qrencode
+check_PROGRAMS += pthread_qrencode
 endif
 
+TESTS = $(check_PROGRAMS)
+
 EXTRA_DIST = test_all.sh test_basic.sh test_configure.sh frame URI_testset.inc CMakeLists.txt
 
 libdecoder_a_SOURCES = decoder.c decoder.h datachunk.c datachunk.h rsecc_decoder.c rsecc_decoder.h
```

Unfortunately this simple patch does not show the result of individual test cases; that would probably require use of a test protocol – either adopting the test programs to TAP, or using a custom driver, as described in the manual.

**Comment by fukuchi** [comment]
Hi @jtojnar,

Thank you for your suggestion. The latest commit f8ceb0d and 7478fff implemented your suggestion to enable 'make check'.
