### ISSUE TITLE
Encoding strangeness

### ISSUE THREAD

**Issue by Wambou** [fukuchi/libqrencode#120]
Dear Mr. Fukuchi,

I am using libqrencode v4.0.0 lately and writing unit tests to check how the library works.

My usage will be encoding URLs and I need case sensitivity for that.
I try to encode alphanumeric values for now.

Here are some examples :
```c++
QRcode* qrcode = QRcode_encodeString("1234567abcdefghij", 0, QR_ECLEVEL_M, QR_MODE_8, 0);

assert(qrcode != nullptr);
assert(qrcode->version == 1); // This works

QRcode_free(qrcode);
```
```c++
QRcode* qrcode = QRcode_encodeString("1234567abcdefghij", 0, QR_ECLEVEL_M, QR_MODE_8, 1);

assert(qrcode != nullptr);

if(qrcode->version == 1) {
    std::cout << "Great!\n";
}
else {
    std::cout << "Why?\n";
} // prints: "Why?"

QRcode_free(qrcode);
```

According to the [standard](http://www.qrcode.com/en/about/version.html), for QR code version 1, I should be able to encode 20 alphanumeric characters, or 128 data bits (mixed), or 14 bytes.
Here I have :
- 17 characters
- 106 data bits
- 17 bytes

But the numbers do not make sense.
Why using case sensitivity makes the QR code bigger ?
How can I compute how many characters I can put in my QR code ?

I looked at the code and I have the impression that it computes data like the standard present "Mixed characters". I did not pushed the comprehension until the end for now.

I have a specific amount of data to store in the QR code and I need to know which version of QR code it will generate. Furthermore, I will use Base64 data inside the QR code and for now, I get random QR code versions, which is not possible to work with.

Thank you in advance for the answers.

Best regards.

**Comment by Wambou** [comment]
After further investigation, I found the reason, it is because of how QR code specification defines "alphanumeric characters", which only includes uppercase letters.

**Comment by fukuchi** [comment]
Hello @Wambou ,

I'm very sorry for missing your question and thank you for your report and investigation.
