### ISSUE TITLE
Unable to find the ./configure file in the package

### ISSUE THREAD

**Issue by shekar2605** [fukuchi/libqrencode#122]
I am unable to find the ./configure file in the package so i am using the ./configure.ac to install but it is throwing error as [root@ip-10-221-2-36 libqrencode]# ./configure.ac
./configure.ac: line 1: syntax error near unexpected token `[__MAJOR_VERSION],'
./configure.ac: line 1: `m4_define([__MAJOR_VERSION], [4])dnl'

**Comment by thebunnyrules** [comment]
I don't know if I was missing some packages but both the configure and autogen scripts were broken for me. 

You can build using cmake:

`cmake .; make`

Be aware the qrencode tool didn't build without libpng-dev. sdl seems to be optional as the dev suggested.

**Comment by thebunnyrules** [comment]
I was able to figure out how to use the ./configure instructions, so I  thought I'd post the answer here:

1) install autogen pre-requists. this will vary from distro to distro but on ubuntu it's:
sudo apt-get install autogen autoconf autotools-dev libtool pkg-config

2) Run autogen:
./autogen.sh

3) Run the configure script as normal:
./configure
make
sudo make install
sudo ldconfig
