### ISSUE TITLE
Truncated input / Control characters?

### ISSUE THREAD

**Issue by jsejcksn** [fukuchi/libqrencode#123]
I attempted to generate a QR code for TOTP authentication, using the example from [google/google-authenticator](https://github.com/google/google-authenticator/wiki/Key-Uri-Format):

```
qrencode -o ./qr.png otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
```

However, the string was truncated before the `&`, resulting a QR code that, when decoded, resulted in `otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP`.

After trying again, but surrounding the input with quotes:

```
qrencode -o ./qr.png "otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example"
```

it worked just fine. Is the ampersand (&) a special character in `bash`? Do I always need to quote strings that contain that character?

**Comment by charmander** [comment]
> Is the ampersand (&) a special character in bash? Do I always need to quote strings that contain that character?

Yes, yes.

This doesn’t really have anything to do with libqrencode; try `echo`.

**Comment by jsejcksn** [comment]
@charmander Alright, thanks!
