### ISSUE TITLE
Is it possible to build the qrencode tool without libpng?

### ISSUE THREAD

**Issue by thebunnyrules** [fukuchi/libqrencode#125]
Hi, first of all, great work on this project. Been using it for years and I really love it. 

I'm trying to minimize the dependencies I have to build to get this project to compile and I only need to only run qrencode in ANSI mode alone so I won't be needing png or any of the other formats. 

I was unable to get the ./configure script to work but cmake .; make worked perfectly.

The only issue I ran into was that it's not able to build qrencode without libpng. Even though cmake says **Build utility tools  ........ = ON** when run without libpng, qrencode is just not compiled and no error is given. When I installed libpng-dev from the ubuntu repo, it compiles.

Is libpng a dependency of qrencode tool or is this a bug?

**Comment by fukuchi** [comment]
Hi,

Thank you for your report. It's not a bug. At this moment, you cannot compile the command line tool without libpng.

I have never imagined that someone wants to compile the tool without PNG support. I'll keep this issue open: someone or I may fix this issue sooner or later.

**Comment by thebunnyrules** [comment]
Hi fukuchi, I was able to get the autogen.sh script to work and have it make a configure script for me. I'm doing all my compiling on a fresh install of ubuntu and it seems I was missing some prerequisite to get autogen to run correctly. Once it ran and produced the configure script, the config script had a --without-png option. So it's all good for me. Might I suggest that you add an autogen step to the instruction in  the Readme.md: 

Compile & install
-----------------
Just try

```
#autogen pre-reqs on ubuntu
sudo apt-get install autogen autoconf autotools-dev libtool pkg-config

./autogen.sh
./configure
make
sudo make install
sudo ldconfig
```

**Comment by fukuchi** [comment]
Hi,

Thank you for the proposal. Yes, we should add more notes about how-to-compile-from-git-tarball. I'll work on it soon.

**Comment by fukuchi** [comment]
Hi @thebunnyrules 

I have added a new option "WITHOUT_PNG" to CMakeLists.txt. Now you can build qrencode without PNG support from cmake:

cmake -DWITHOUT_PNG=YES .
make
