### ISSUE TITLE
error on plugin added

### ISSUE THREAD

**Issue by FndNur1Labs** [fukuchi/libqrencode#126]
[  0%] Building C object CMakeFiles/qrencode.dir/libqrencode/mask.c.o
/root/coins/newgui/libqrencode/mask.c:34:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_writeFormatInformation(int width, unsigned char *frame, int mask, QRecLevel level)
                   ^
/root/coins/newgui/libqrencode/mask.c: In function ‘Mask_makeMask’:
/root/coins/newgui/libqrencode/mask.c:177:2: warning: implicit declaration of function ‘Mask_writeFormatInformation’ [-Wimplicit-function-declaration]
  Mask_writeFormatInformation(width, masked, mask, level);
  ^
/root/coins/newgui/libqrencode/mask.c: At top level:
/root/coins/newgui/libqrencode/mask.c:188:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcN1N3(int length, int *runLength)
                   ^
/root/coins/newgui/libqrencode/mask.c:221:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcN2(int width, unsigned char *frame)
                   ^
/root/coins/newgui/libqrencode/mask.c:244:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcRunLengthH(int width, unsigned char *frame, int *runLength)
                   ^
/root/coins/newgui/libqrencode/mask.c:272:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcRunLengthV(int width, unsigned char *frame, int *runLength)
                   ^
/root/coins/newgui/libqrencode/mask.c:300:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_evaluateSymbol(int width, unsigned char *frame)
                   ^
/root/coins/newgui/libqrencode/mask.c: In function ‘Mask_mask’:
/root/coins/newgui/libqrencode/mask.c:348:3: warning: implicit declaration of function ‘Mask_evaluateSymbol’ [-Wimplicit-function-declaration]
   demerit += Mask_evaluateSymbol(width, mask);

Qrencode cmake

set(QRENCODE_LIB qrencode)

file(GLOB QRENCODE_SOURCES RELATIVE ${CMAKE_SOURCE_DIR} libqrencode/*.c)
list(REMOVE_ITEM QRENCODE_SOURCES libqrencode/qrenc.c)
file(GLOB QRENCODE_HEADERS libqrencode/*.h)

list(APPEND my_definitions "__STATIC=static")
list(APPEND my_definitions "MAJOR_VERSION=4")
list(APPEND my_definitions "MINOR_VERSION=0")
list(APPEND my_definitions "MICRO_VERSION=0")
if(WIN32)
  list(APPEND my_definitions "inline=__inline")
endif(WIN32)
add_library(${QRENCODE_LIB} ${QRENCODE_SOURCES} ${QRENCODE_HEADERS})
set_target_properties(${QRENCODE_LIB} PROPERTIES COMPILE_DEFINITIONS "${my_definitions}")

**Comment by fukuchi** [comment]
Hi,

I cannot figure out the details why it failed - you may want to ask the developers of 'coins'.
Anyway, probably the latest update will fix this issue.

**Comment by FndNur1Labs** [comment]
thank you i waiting the patch. actually i found on some this. im developer
that coin with old we can do and fixed. i will send the full problems
script later.
