### ISSUE TITLE
Unscannable QR Codes produced

### ISSUE THREAD

**Issue by jhihn** [fukuchi/libqrencode#134]
With:
QRcode *code = QRcode_encodeString8bit(string.constData(), 0, QR_ECLEVEL_L);
int pixelsPerBlock = out.width() / code->width;
for (int y=0; y<code->width; y++) {
for (int x=0; x< code->width; x++) {
painter.setBrush( code->data[(y*code->width)+x] & 1 ? blackBrush: whiteBrush);
painter.drawRect(x*pixelsPerBlock,y*pixelsPerBlock, code->width*pixelsPerBlock, code->width*pixelsPerBlock);
}
}

I sometimes get a QRCode (attached) that is not scannable by "Barcode Scanner by Zxing" in the Android play store. (Which after trying many seems the best) It has copied blocks on the right and bottom.

It seems that width is sometimes smaller (or larger) than it should be? Am I doing something wrong?

![screen shot 2018-08-30 at 2 10 13 pm](https://user-images.githubusercontent.com/5502325/44871443-c82c8980-ac60-11e8-8035-3572168bd3e1.png)

**Comment by jhihn** [comment]
Nevermind, I'm an idiot.  It should not be code->width*pixelsPerBlock, just pixelsPerBlock to the drawing API

**Comment by fukuchi** [comment]
Thanks. BTW, cool image, isn't it? ;)
