### ISSUE TITLE
./autogen.sh: line 28: Command not found

### ISSUE THREAD

**Issue by Mulf** [fukuchi/libqrencode#139]
I was trying to use libqrencode on windows. I entered into the directory of librencode with CygWin shell. But when I tried to run autogen.sh with the code : 
`sh ./autogen.sh`,
 it kept showing that ./autogen.sh: line 28: Command not found. 
I got the same result when i tried another method:
`chmod u+x ./autogen.sh`
'./autogen.sh'
Could anyone help me with that?

**Comment by Mulf** [comment]
This issued has been sloved by  [stackflow](https://stackoverflow.com/questions/55112305/autogen-sh-line-28-command-not-found-139/55115427#55115427).

**Comment by fukuchi** [comment]
Hi @Mulf ,

Thank you for the report and telling us the Q&A at stackoverflow. Great help.
