### ISSUE TITLE
Error in configuring libqrencode with CygWin :   configure: error: no acceptable ld found in $PATH

### ISSUE THREAD

**Issue by Mulf** [fukuchi/libqrencode#140]
I was trying to install and compile libqrencode by following  the instructions in [ FUKUCHI Kentaro's web with **CygWin**.  pages](https://fukuchi.org/works/qrencode/) . When I proceeded to the step:

> Now you are ready to compile the library and tool. Type the following commands:

```
./configure
make
sudo make install
sudo ldconfig
```
I typed `./configure` in the command line, but got remarks as following 

> $ ./configure
checking build system type... x86_64-unknown-cygwin
checking host system type... x86_64-unknown-cygwin
checking target system type... x86_64-unknown-cygwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... cl.exe
checking whether the C compiler works... yes
checking for C compiler default output file name... conftest.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... obj
checking whether we are using the GNU C compiler... no
checking whether cl.exe accepts -g... yes
checking for cl.exe option to accept ISO C89... none needed
checking whether cl.exe understands -c and -o together... no
checking dependency style of /cygdrive/c/Users/Administrator/Desktop/libqrencode-master/use/compile cl.exe... none
checking for an ANSI C-conforming const... yes
checking for inline... __inline
checking how to run the C preprocessor... /cygdrive/c/Users/Administrator/Desktop/libqrencode-master/use/compile cl.exe -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for non-GNU ld... no
configure: error: no acceptable ld found in $PATH

How could I fix this problem? Thanks.

**Comment by fukuchi** [comment]
Hi @Mulf 

While I'm not familiar with Cygwin. I guess that you did not install compilers. At least you need to install gcc and make packages, as far as I know.

**Comment by Mulf** [comment]
Yes, you are right. There is no gcc in my computer, so I can't configure. 
Now I successfully configure the files, but it turns out be some linux files. Is that possible to make a windows lib from your code? Thank you.
