### ISSUE TITLE
qrcode decoder

### ISSUE THREAD

**Issue by charlesvvdn** [fukuchi/libqrencode#141]
we successfully encoded a qrcode using the given c code but how can i decode a qrcode using the same

**Comment by AnamikaAhmed** [comment]
I am stuck in quite the same issue. I hope someone replies.

**Comment by jerabaul29** [comment]
zbarimg maybe?

https://github.com/ZBar/ZBar

**Comment by fukuchi** [comment]
Thank you all for the discussion. As commented by @jerabaul29, I recommend you to use zbarimg. [quirc](https://github.com/dlbeer/quirc) is also useful - very small and easy to hack.
