### ISSUE TITLE
request: support light background text in UTF8 mode

### ISSUE THREAD

**Issue by bjmgeek** [fukuchi/libqrencode#142]
I love the fact that I can make a qr code, with the `qrencode` command line utility, with `-t UTF8`, that I can save as a text file, and open in e.g. Notepad in Windows, which displays the code. The only problem is that the default color scheme of Notepad is black text on a white background.  That means in order for the code to scan, I have to select the text.  Please add an option so the code will be generated to use dark text on a light background.

thanks.

**Comment by d4ndo** [comment]
UTF8 does not support color, does it?. Following UTF8 chars are used:

- half block (▄)  e2 96 84,
- full block (█) e2 96 88,
- and whitespace( ). 20

So it depends how your editor is interpreting the UTF8 chars. Also whitespace are limited. There are a view: vertical tab, horizontal tab, whitespace etc. some are just for printing.

**Comment by d4ndo** [comment]
On the other hand it could be possible by just switching the full block with a whitespace and useing this half block (▀) e2 96 88.

**Comment by d4ndo** [comment]
You could use sed to swap the chars:

`qrencode -t UTF8 Hi | sed -e 's/▄/▀/g' -e 's/█/X/g' -e 's/ /█/g' -e 's/X/ /g' `

**Comment by BrainStone** [comment]
I'd probose the `UTF8i` type. Similar to the `ASCIIi` type. All it does is print it in reverse, so it works for black text on white background.

**Comment by fukuchi** [comment]
Hi all,

Qrencode 4.1.0 provides UTF8i option and solves this issue.

BTW, as @BrainStone pointed out, the meaning of 'i' is a little bit confusing, but it seems too late to change to make them consistent. I'll add a note about this inconsistency to README or somewhere in the next release.

**Comment by BrainStone** [comment]
I propose this to be changed with the next major/breaking update.

**Comment by fukuchi** [comment]
Hi,

This issue has been fixed in e5ac8ca. This fix will be released in the next major update, 5.0.0.

Thank you for your suggestion.
