### ISSUE TITLE
Coverity issue of QRinput_encodeModeNum

### ISSUE THREAD

**Issue by xiaoyur347** [fukuchi/libqrencode#143]
Coverity complains of the follow line
https://github.com/fukuchi/libqrencode/blob/master/qrinput.c Line 449
       } else if(entry->size - words * 3 == 2) {
		val  = (unsigned int)(entry->data[words*3  ] - '0') * 10;
		val += (unsigned int)(entry->data[words*3+1] - '0');
		BitStream_appendNum(bstream, 7, val);
		if(ret < 0) return -1; //here
	}
"
Medium:Unchecked return value(CHECKED_RETURN)
CWE252: Value returned from a function is not checked for errors before being used
Calling "BitStream_appendNum" without checking return value (as is done elsewhere 31 out of 34 times).
"
I'm curious whether we should check this BitStream_appendNum() result or not.
Thanks.

**Comment by fukuchi** [comment]
Thank you for the report. The issue has been fixed now.
