### ISSUE TITLE
Monospace font causes improper rendering

### ISSUE THREAD

**Issue by MrButlerTron** [fukuchi/libqrencode#148]
Using qrencode -t ansituf8 on Ubuntu Linux over SSH from a Windows machine using KiTTY or Putty the QR codes do not render properly.  I am not sure if there is a fix for this other than just not using a monospace font.
![image](https://user-images.githubusercontent.com/45610889/70449471-0e7db480-1a70-11ea-836d-57b729f11324.png)

I was using *Inconsolata* and the problem goes away when I go to the default *Courier New*.  It could just be that specific font. I have not yet had a chance to try other fonts.

**Comment by fukuchi** [comment]
ANSI-UTF8 mode highly depends on Unicode's "block elements" characters.
https://en.wikipedia.org/wiki/Block_Elements

I'm afraid that Inconsolata does not support the block elements.

**Comment by MrButlerTron** [comment]
Thanks!  That explains it.  I will check my other fonts and now I'll know for the future.

**Comment by GHPS** [comment]
Short comment: I had the same issue with InconsolataGo Nerd Mono and found after some testing that even Ubuntu Mono and Mitra Mono affected. 

Switching from "-t ansiutf8" to "-t ansi256" or "-t ansi" made the qr code usable again
(although it is not that pretty to look at).

 "Inconsolata-g for Powerline" is also not affected - so switching to that can be an option.
