### ISSUE TITLE
PNG output is disabled at compile time. No output generated.

### ISSUE THREAD

**Issue by ljchen1129** [fukuchi/libqrencode#149]
mac OS zsh teminal

`qrencode -o so.png "http://stackoverflow.com"
PNG output is disabled at compile time. No output generated.`

![image](https://user-images.githubusercontent.com/13548479/73525343-fad84400-4449-11ea-934e-791c7bbbed3a.png)

**Comment by fukuchi** [comment]
If you compiled qrencode by yourself, please install libpng-dev or something like that, then recompile qrencode.

**Comment by ljchen1129** [comment]
thank you！
I reinstalled brew and then reinstalled qrencode and it worked out.
