### ISSUE TITLE
qrencode -t ansiutf8 glitch

### ISSUE THREAD

**Issue by bes-internal** [fukuchi/libqrencode#150]
`$ head /dev/urandom |qrencode -t ansiutf8` 

produced

![image](https://user-images.githubusercontent.com/2046529/73882344-ec878f00-4872-11ea-8387-14a77f9c8068.png)

where � is:
```
length: 1
U+FFFD
REPLACEMENT CHARACTER
&#65533;
&#xFFFD;
utf8 hex: EF BF BD
```

**Comment by fukuchi** [comment]
Can you tell us what font is used on your terminal?

**Comment by bes-internal** [comment]
DejaVu Sans Mono
pretty popular font ...

**Comment by fukuchi** [comment]
Sorry, I could not reproduce this. As far as I know, there is no chance to output U+FFFD or any other special characters than ▀▄█. A possible explanation is a communication error between the shell and the terminal, but I'm not sure.

If you have the same issue still, please let me know more details of the environment.
