### ISSUE TITLE
problem encoding / decoding binary data

### ISSUE THREAD

**Issue by jerabaul29** [fukuchi/libqrencode#152]
This is similar to the github issue: https://stackoverflow.com/questions/60506222/encode-decode-binary-data-in-a-qr-code-using-qrencode-and-zbarimg-in-bash

I have some binary data that I want to encode in a qr-code and then be able to decode, all of that in bash. After a search, it looks like I should use qrencode for encoding, and zbarimg for decoding. After a bit of troubleshooting, I still do not manage to decode what I had encoded

Any idea why? Currently the closest I am to a solution is:

```
$ dd if=/dev/urandom bs=10 count=1 status=none > data.bin
$ xxd data.bin
00000000: b255 f625 1cf7 a051 3d07                 .U.%...Q=.
$ cat data.bin | qrencode -l H -8 -o data.png
$ zbarimg --raw --quiet data.png | xxd
00000000: c2b2 55c3 b625 1cc3 b7c2 a051 3d07 0a    ..U..%.....Q=..
```

More specifically, I am wondering what explains this problem among the possible following points (maybe it is something else and I am missing something though):

- some error in my flags used with qrencode and / or zbarimg
- some error in how I use xxd (would be quite surprised, but never know)
- some incompatibility of format / implementation problem from qrencode and / or zbarimg

Any suggestions?

**Comment by jerabaul29** [comment]
Ok, this needs some base64 wrapping, not sure why. Looks like it is rather an issue with zbarimg than with qrencode. Feel free to close if you agree.

**Comment by jerabaul29** [comment]
Sorry, this is actually not solved, because using a base64 encoding as suggested in the (now de-)accepted answer would double the size required.

**Comment by fukuchi** [comment]
Hi @jerabaul29,

It seems that the problem of zbarimg. As answered in the thread of the stackoverflow, this problem seems to be solved by the latest zbarimg.
