### ISSUE TITLE
qrencode adds trailing newline to text

### ISSUE THREAD

**Issue by sauerj** [fukuchi/libqrencode#153]
I noticed that `qrencode` adds to all texts a trailing `\n`

Assuming we want to encode the text "Hello World!":
```
$ echo "Hello World!" | xxd
$ 00000000: 4865 6c6c 6f20 576f 726c 6421 0a         Hello World!.
```

```
$ echo "Hello World!" | qrencode -o - | zbarimg --raw -q - | xxd
$ 00000000: 4865 6c6c 6f20 576f 726c 6421 0a0a       Hello World!..
```
Notice the second `0x0a`

When the string is directly passed as an argument the same happens: a trailing newline is appended. Internally the strings ends with a `!` (before `\0`):
```
$ qrencode -o - "Hello World!"  | zbarimg --raw -q - | xxd
$ 00000000: 4865 6c6c 6f20 576f 726c 6421 0a         Hello World!.
```

I assume when a input string does not end with `\n` a newline character should be appended. But not when there is already a newline.

I tried to track down the line where is may happens but I did not found it. Maybe you can give me a hint where I can search.

What I know so far:

* When qrencode enters `QRinput_encodeBitStream()`  `entry->data` is still correct

**Comment by charmander** [comment]
It’s part of zbarimg’s output, not the QR code produced by qrencode.

**Comment by fukuchi** [comment]
Hi,

As @charmander pointed out, the newline character is added by zbarimg. Qrencode does not add a newline character.
