### ISSUE TITLE
-M doc and error message lack enough info to enable use

### ISSUE THREAD

**Issue by jidanni** [fukuchi/libqrencode#154]
```
$ qrencode -M -o - A|wc -c
Version must be specified to encode a Micro QR Code symbol.
0
```
OK but do mention that on the man page at -M!

```
$ qrencode -M -v 1 -o - A|wc -c
Failed to encode the input data: Invalid argument
0
```

Well I guess we'll give up then.

Wait, let's try some other numbers.

```
$ qrencode -M -v 11 -o - A|wc -c
Version should be less or equal to 4.
0
```

Ah... we're getting somewhere.

```
$ qrencode -M -v 4 -o - A|wc -c
250
$ qrencode -M -v 3 -o - A|wc -c
234
$ qrencode -M -v 2 -o - A|wc -c
209
$ qrencode -M -v 1 -o - A|wc -c
Failed to encode the input data: Invalid argument
0
```

If -v 11 causes
"Version should be less or equal to 4."
then using -v 1 should surely say
"Version should be greater or equal to 2.",
and not the opaque
"Failed to encode the input data: Invalid argument"

And the man page should say at -M: use with -v [2-4].

P.S., I'm using
```
$ qrencode -V
qrencode version 4.0.2
```

**Comment by fukuchi** [comment]
Hi @jidanni,

Thank you for your suggestion and very sorry for my late response. The latest commits to the development branch solve this issue. What I've done are:
  - Micro QR Code no longer requires to specify the version number. Qrencode automatically selects the appropriate version number for the input data.
  - the man page has been updated. The limitation of the version number for Micro QR Code is now described.
  - the error message has been improved.

The next release of qrencode (version 4.1.0) will include these improvements.
