### ISSUE TITLE
manpage: put -o into SYNOPSIS as it is required

### ISSUE THREAD

**Issue by jidanni** [fukuchi/libqrencode#155]
Manpage says
```
SYNOPSIS
      qrencode [OPTION]...  [STRING]
```
well that should be
```
      qrencode -o <FILENAME> [OPTION]...  [STRING]
```
as FILENAME is required.

**Comment by charmander** [comment]
It isn’t required for the text-based output types, including SVG.

**Comment by jidanni** [comment]
OK. All I know is the man page has three examples in the EXAMPLES
section, and all involve -o. So perhaps add an non--o example so we know what
you are talking about.

**Comment by fukuchi** [comment]
Hi @jidanni,

Thank you all for your suggestion. I have fixed the manpage as following. I think this fix is user-friendly and solves the issue raised by @charmander.
```
SYNOPSIS
       qrencode [-o FILENAME] [OPTION]...  [STRING]
```
