### ISSUE TITLE
Compile fails with WITH_TESTS set as ON under Windows

### ISSUE THREAD

**Issue by mtl1979** [fukuchi/libqrencode#156]
prof_qrencode.c
C:\build\git\talleo-gui\libqrencode\tests\prof_qrencode.c(3): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [C:\build\git\talleo-gui\build-win\libqrencode\tests\prof_qrencode.vcxproj]
  Building Custom Rule C:/build/git/talleo-gui/libqrencode/tests/CMakeLists.txt
  pthread_qrencode.c
C:\build\git\talleo-gui\libqrencode\tests\pthread_qrencode.c(3): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [C:\build\git\talleo-gui\build-win\libqrencode\tests\pthread_qrencode.vcxproj]

**Comment by fukuchi** [comment]
Hello @mtl1979,

Thank you for the report. Can you test the following quick fix?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2bb1b6d..f33da2e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -32,7 +32,7 @@ check_include_file(stdlib.h   HAVE_STDLIB_H  )
 check_include_file(strings.h  HAVE_STRINGS_H )
 check_include_file(string.h   HAVE_STRING_H  )
 check_include_file(getopt.h   HAVE_GETOPT_H  )
-check_include_file(sys/time.h HAVE_SYS_TIME_H)
+check_include_file(time.h HAVE_SYS_TIME_H)
 
 check_function_exists(strdup HAVE_STRDUP)
```
Then remove CMakeCache.txt and run cmake again.

**Comment by mtl1979** [comment]
At least ```tests/prof_qrencode.c``` doesn't even use ```HAVE_SYS_TIME_H``` ...

If I tell it to check if ```<time.h>``` exists, it returns 1, as ```C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\time.h``` exists

**Comment by fukuchi** [comment]
Thank you for the report and the pull request. I have applied a similar fix to pthread_qrencode.c and it worked nicely.
