### ISSUE TITLE
Do you have a plan to support 1D barcode? such as UPC-A, UPC-E, EAN-2 and so on

### ISSUE THREAD

**Issue by elicec** [fukuchi/libqrencode#159]
Do you have a plan to support 1D barcode? such as UPC-A, UPC-E, EAN-2 and so on

**Comment by fukuchi** [comment]
Libqrencode will never support any 1D barcode nor any other barcode systems. I recommend you to use [ZXing](https://github.com/zxing/zxing) or [Zint](https://zint.github.io/) instead.
