### ISSUE TITLE
Cannot build on Ubuntu 18.04

### ISSUE THREAD

**Issue by a6q** [fukuchi/libqrencode#170]
libpng12-dev literally doesn't exist anymore on any Ubuntu distros or repos after 16.04. It was superseded by libpng-dev, but installing this makes no difference. "configure" still throws the same warning "LIBPNG is required to build the utility tools, temporarily disabled".

Not sure why it's using such a ridiculously outdated package for something that's still being actively updated. Please fix this.

**Comment by fukuchi** [comment]
Thank you @a6q for the report. 'libpng12-dev' was only described in the documents, not specified in any build scripts which means simply you can build qrencode with libpng-dev.

I have fixed this issue now. Thank you again for the report.
