### ISSUE TITLE
wrong error correction level

### ISSUE THREAD

**Issue by mounyia** [fukuchi/libqrencode#173]
We use libqrencode QRcode_encodeString() to generate a QR code.
The problem is that the input parameter QRecLevel only sometimes corresponds to the output (QR code). We cannot understand this.

Example:
- Request QR_ECLEVEL_L -> Output is L
- Request QR_ECLEVEL_M -> Output is Q
- Request QR_ECLEVEL_Q -> Output is M
- Request QR_ECLEVEL_H -> Output is H

but can also be different

We used this for checking the error correction level output :https://blog.qrstuff.com/2011/12/14/qr-code-error-correction

**Comment by fukuchi** [comment]
Hello @mounyia, thank you for the report.

I'm trying to reproduce the bug but still not found it. Could you please send the generated images and input texts?
Plus, please let me know the version number of the libqrencode you've tested.

**Comment by mounyia** [comment]
Hi @fukuchi 

we use the newest Version 4.1.1

the input text is: 
'SPC\n0200\n1\nCH3430769035752092002\nK\nW. Beyeler AG\nIn den Wyden 3\n4143 Dornach\n\n\nCH\n\n\n\n\n\n\n\n235.75\nCHF\nK\nFuxfood GmbH  c/o Maurizio Laneri\nOberer Mühlerain 487\n5072 Oeschgen\n\n\nCH\nQRR\n000000000300248800000000010\n\nEPD\n//S1/10/3002488.001/11/210114'

the requested QRecLevel is M 

attached my output. Now, I have a error correction level of Q
![QR4](https://user-images.githubusercontent.com/77663978/105138171-d2cb7000-5af4-11eb-9019-0fe374f798b3.jpg)

**Comment by fukuchi** [comment]
Okay, I've managed to figure out the issue.

The image you've posted is encoded with ECC level M as you expected. The image has been flipped along the diagonal. The image attached to this post is the correct output. 
![spc-image4](https://user-images.githubusercontent.com/637330/105292608-42785280-5bfc-11eb-9071-ecb72fc3f7ad.png)

I wonder why the image had been flipped. What tool did you use to put the icon located at the center of the image?

**Comment by fukuchi** [comment]
BTW, you can edit your last post to hide the private information.

**Comment by mounyia** [comment]
We use our own tool for generating PDFs (Oregator).

The small image is simply placed over the QR code by our tool.

The icon is not the problem. Even if I turn it off I get the same wrong qr image.

**Comment by fukuchi** [comment]
I think that your tool flips the image. Please check your code whether handles the generated data incorrectly or not. The following code snippet is the typical way to handle the data. Double-checking the order of x and y is recommended.

```
QRcode *qrcode;
 
qrcode = QRcode_encodeString("TEST", 0, QR_ECLEVEL_M, QR_MODE_8, 1);
if(qrcode == NULL) abort();
 
for(int y = 0; y < qrcode->width; y++) {
    for(int x = 0; x < qrcode->width; x++) {
        if(qrcode->data[y * qrcode->width + x] & 1) {
            draw_black_dot(x, y);
        } else {
            draw_white_dot(x, y);
        }
    }
}
 
QRcode_free(qrcode);
```

**Comment by mounyia** [comment]
That was the problem: x and y were reversed.

Thank you very much. Without your help we would never have figured that out!
