### ISSUE TITLE
Problems with compiling

### ISSUE THREAD

**Issue by ghost** [fukuchi/libqrencode#27]
Hello.
In first time, I want to apologize for my English. I am Spanish and I have not a good English.
When I go to compile test (using make), I go to tests's folder and write in my shell:
make
My problem is:

test_qrinput.o: In function `check_lengthOfCode':
/home/myPCl/Descargas/qrencode-3.4.2/tests/test_qrinput.c:444: undefined reference to`QRinput_mergeBitStream'
/home/myPC/Descargas/qrencode-3.4.2/tests/test_qrinput.c:446: undefined reference to `QRinput_lengthOfCode'
/home/myPC/Descargas/qrencode-3.4.2/tests/test_qrinput.c:372: undefined reference to`QRinput_insertStructuredAppendHeader'
/home/myPC/Descargas/qrencode-3.4.2/tests/test_qrinput.c:643: undefined reference to `QRinput_splitEntry'

Can you help me?

Thanks. :D

**Comment by adelinastanciu** [comment]
Thanks for sharing, I was running make from tests directory and it didn't work.
