### ISSUE TITLE
qrencode fails with large input data

### ISSUE THREAD

**Issue by KingDuckZ** [fukuchi/libqrencode#31]
As shown here http://www.qrcode.com/en/about/version.html (please click the 31-40 button to see the table) level M qr codes should hold up to 2331 bytes of raw data.
I run qrencode in a script (http://pastebin.com/3LuCtfP1). To easily reproduce the problem I do the following:

Take some large file (qrspec.h from libqrencode is just fine), then:
$ cp qrspec.h testfile.h
$ truncate -s 2331 testfile.h
$ cat testfile.h | qrencode --8bit --level=M --output=testfile.png

Failed to encode the input data: Numerical result out of range

According to the table linked above, the size should fit. If you add a --symversion=40 to the command line the problem is fixed, but then the bash script would produce unnecessarily large QR codes even for small data unless some logic is added.

My understanding of the code is that the input version (0 in my case) is sent down up to QRspec_maximumWords(), which then returns a faulty number. Up at the beginning of the backtrace though, QRcode_encodeDataReal() has the following parameters:

const unsigned char *data, int length, int version, QRecLevel level, int mqr

Given the table I linked above, a simple test on version == 0 should be enough to trigger automatic minimum required version guessing. I'm not sure if this is the right solution, I'd rather argue the QRspec_maximumWords() should just work, but I don't understand what it's doing with the 4x3 matrix and my fix should ensure version 0 is never passed down.

I tried this on qrencode 3.4.2 from my distro's repository and on qrencode build from the github repository at tag v3.4.3. The problem happens in both.

**Comment by persianstarr** [comment]
Does QREncode really conform to the QR Standard specifications regarding max. characters?

According to wiki: https://en.wikipedia.org/wiki/QR_code

Numeric only	7,089	3⅓	0, 1, 2, 3, 4, 5, 6, 7, 8, 9
Alphanumeric	4,296	5½	0–9, A–Z (upper-case only), space, $, %, *, +, -, ., /, :

However I am getting much lower max. characters, around 2000 for alphanumeric and around 5000 for numeric values, any ideas? where is this set, how can it be increased\fixed to support the QR standard?

Thanks!

**Comment by fukuchi** [comment]
Attached image includes 7089 of "1", generated by the latest qrencode.

![test](https://cloud.githubusercontent.com/assets/637330/8692381/b19f928e-2b08-11e5-9999-fe522c862639.png)

**Comment by toogley** [comment]
I can still reproduce this issue, even with the newest version (3.4.4):

    $ ./qrencode -o test.png < ~/private.key

    Failed to encode the input data: Numerical result out of range

The private.key file is the output of `$ gpg --export-secret-keys --armor`, which is a 4096 Bit key.
`

**Comment by RELAXccc** [comment]
> Attached image includes 7089 of "1", generated by the latest qrencode.
> 
> ![test](https://cloud.githubusercontent.com/assets/637330/8692381/b19f928e-2b08-11e5-9999-fe522c862639.png)

What parameters did you use? Can not get this to work atm

**Comment by fukuchi** [comment]
$ ruby -e "print '1'*7089" > 7089.txt
$ qrencode -o 7089.png -r 7089.txt

**Comment by un1ntentional** [comment]
confirmed still a piece of crap 
```
gpg --export --armor alg0d@keybase.io |wc -c
4617
gpg --export --armor alg0d@keybase.io | qrencode -8 -lM -o test.png
Failed to encode the input data: Input data too large
toor@linux-zoxo:~> qrencode --version
qrencode version 4.0.0
Copyright (C) 2006-2017 Kentaro Fukuchi
toor@linux-zoxo:~> 

```

**Comment by charmander** [comment]
@un1ntentional if my math is correct, 4 617 > 2 953 (the limit with `-lL`)

**Comment by ralyodio** [comment]
has anyone found a fix for this yet? I'm trying to scan an ascii private gpg key on `pass` for iPhone and it won't scan.

mine is 5196

**Comment by fukuchi** [comment]
Hi @chovy,

5196 byte is too large to generate a QR code. The maximum size is 2953.

**Comment by ElectricRCAircraftGuy** [comment]
@fukuchi , I'm confused. [Here](https://github.com/fukuchi/libqrencode/issues/31#issuecomment-498694462) you said you generated 7089 bytes of the number `1`, so how is the limit 2953? Also, the QR code max size should be larger--4296 chars--no? See: https://www.keyence.com/ss/products/auto_id/codereader/basic_2d/qr.jsp

Oh...that's 7089 numeric values (per my link above), which is the max for numbers. But that link says the max for alphanumeric is 4296, so why are you saying 2953?

Also, it would be useful to put these max limits into the error message when a file is too large.

**Comment by lemniscati** [comment]
@ElectricRCAircraftGuy See https://www.qrcode.com/en/about/standards.html
The maximum size for a data of 8-bit bytes (binary) is 2,953.
