### ISSUE TITLE
./configure: unexpected token with Ubuntu 12.04

### ISSUE THREAD

**Issue by BigMcLargeHuge** [fukuchi/libqrencode#54]
Hi There,

I'm attempting to compile qrencode in Ubuntu 12.04 and am getting the following errors;

./configure.ac: line 1: syntax error near unexpected token `[__MAJOR_VERSION],'
./configure.ac: line 1:`m4_define([__MAJOR_VERSION], [3])dnl'

Might there be something that I'm woefully overlooking?  (It's entirely possible)

**Comment by fukuchi** [comment]
Ubuntu 12.04 is obsolete.
