### ISSUE TITLE
Passing string via STDIN chokes on '-' character

### ISSUE THREAD

**Issue by jottr** [fukuchi/libqrencode#57]
`qrencode version 3.4.4`

```
$ qrencode '-f' -o qrcode.png

qrencode: invalid option -- f
Try `qrencode --help' for more information.
```
Why does this happen even when I am using [strong quotes](http://wiki.bash-hackers.org/syntax/quoting#strong_quoting)?

**Comment by tklauser** [comment]
```qrencode -o qrcode.png -- -f```

should work. The ```--``` causes any following arguments not to be treated as options.
