### ISSUE TITLE
CLI program ignores version setting when data is too large to fit

### ISSUE THREAD

**Issue by minus7** [fukuchi/libqrencode#62]
Trying to generate a V3 (explicitly set via -v 3) H alphanumeric QR code, which has a maximum of 35 characters. When passing 36 or more characters, the CLI program will silently increase the QR code version to 4.
`qrencode -s 10 -l H -v 3 -i -o /tmp/v3.png 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'` generates a V3 code
`qrencode -s 10 -l H -v 3 -i -o /tmp/v4.png 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'` generates a V4 code

Instead of just increasing the version it should show an error, or the documentation should clearly label -v as minimum version setting.

**Comment by fukuchi** [comment]
Thank you for your suggestion. Because I would like to avoid showing an error, simply I have updated the usage. See 7ee99e2726.

**Comment by minus7** [comment]
Nice solution, thanks.
