### ISSUE TITLE
Make png optional

### ISSUE THREAD

**Issue by oneru** [fukuchi/libqrencode#70]
I'm working toward using qrencode to generate a qr code for a luci app in openwrt. I think I can use the svg output to display the qr code in the browser. 

Would it be possible to make libpng an optional dependency? When a 4 meg router only has a few hundred K of free space, libpng is quite a large package.

I understand I can use --without-tools and not build the qrencode program, but I would like to use qrencode, just not to create a png file.

Thanks,
Jonathan Bennett

**Comment by oneru** [comment]
I've made this work, but my patch that rips png out of qrencode is quite ugly. The end results are quite nice, though. http://incomsystems.biz/fwknop-interface-qr.png

I would still prefer a --disable-png switch for configure, if that is something you would be willing to do.

**Comment by fukuchi** [comment]
Hi,

This issue has been solved with the latest commit. Try "--without-png".

**Comment by oneru** [comment]
Excellent, I'll test this out in OpenWrt to make sure it works as intended.  Thank you very much!
