### ISSUE TITLE
How to use the compiler msvc?

### ISSUE THREAD

**Issue by KangLin** [fukuchi/libqrencode#78]
How to use the compiler msvc?

I recommend using cmake management the project.

**Comment by aleksey-nikolaev** [comment]
This libqrencode fork https://github.com/LadislavSopko/libqrencode also has cmake. I do not understand which is better?
And how to resolve this error:
qrenc.c(28): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
when compiled on msvc2015
