### ISSUE TITLE
Autoconf tool:

### ISSUE THREAD

**Issue by PieterDeGaaij** [fukuchi/libqrencode#79]
Hi,

I am trying to configure and compile the source code on a Solaris 10 server.
But when I run autogen.sh, I got this error:
./autogen.sh
configure.ac:52: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.

Do you know what's wrong and how to solve this problem ?

Thanks in advance,
with regards,
Pieter de Gaaij

**Comment by fukuchi** [comment]
Did you install pkg-config? Some articles associate this error with pkg-config.

https://bugzilla.redhat.com/show_bug.cgi?id=921817
https://blogs.oracle.com/mandy/entry/autoconf_weirdness

**Comment by PieterDeGaaij** [comment]
Thanks for your comment, I have appreciated very much, because the problem has been solved.
I have added the package pkg-config on my Solaris Server and I created the libpng.pc.
Then the configure script completed successfully.
With regards,
Pieter de Gaaij

**Comment by fukuchi** [comment]
Good to hear.
