### ISSUE TITLE
3.4.4 not pushed to GitHub

### ISSUE THREAD

**Issue by mgorny** [fukuchi/libqrencode#84]
The homepage lists 3.4.4 release as the newest but there is no such tag/release on GitHub.

**Comment by adolfogc** [comment]
I also noticed there is no release for that version, but the README in the 3.4 branch mentions 3.4.4. as the current version and has 61fe834 as its last commit; the v3.4.3 tag has 055f441 as its last commit. See https://github.com/fukuchi/libqrencode/tree/3.4

**Comment by fukuchi** [comment]
Hi, thank you for letting me know the issue. Now I pushed the v3.4.4 tag to the repository, which points to the commit 8d4585.
