### ISSUE TITLE
If I use the --without-tools option, how can I display the QR code to the user to scan?

### ISSUE THREAD

**Issue by TheWingineer** [fukuchi/libqrencode#86]
I have the generated bitmap array, but how do I turn that into an image that I can display to users if I use the --without-tools option? Ideally I'd like to have the code in a PNG or PIL object instead of a bitmap array.

**Comment by fukuchi** [comment]
"--without-tools" is for developers or package managers who needs only the library. If you want to develop your own software that displays the QR code, tests/view_qrcode.c would be a good sample.
