### ISSUE TITLE
problem for CMake compilation : missing definition "STATIC_IN_RELEASE" 

### ISSUE THREAD

**Issue by gotoo77** [fukuchi/libqrencode#87]
i encountered this problem while trying to compile using cmake (using CLion IDE )

when i comment and replace with this:
#ADD_DEFINITIONS(-D__STATIC=)
ADD_DEFINITIONS(-DSTATIC_IN_RELEASE=)

problem seems solved.
Do you confirm ?

(i found the following info in the changelog :
	* configure.ac, *.c:
	  - Renamed __STATIC macro to STATIC_IN_RELEASE. (follows C99 standard)
)

i guess modification has ben made in configure.ac (autoconf) but not reported in CMake, correct?

**Comment by fukuchi** [comment]
It's now fixed by f0f0dd3f, as far as I know. Please try the latest source tree.
