### ISSUE TITLE
Problem while trying to use automake/autoconf

### ISSUE THREAD

**Issue by gotoo77** [fukuchi/libqrencode#88]
i have this logs:

[user@userlibqrencode]$ autoconf
configure.ac:26: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:34: error: possibly undefined macro: AC_PROG_LIBTOOL
[user@userlibqrencode]$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in use "."/use

what should i do ? what am i doing wrong?
thx by advance :)

**Comment by fukuchi** [comment]
Please let me know the version of your autoconf/automake. Here I tested the latest source tree with the followings and no error occurs.

* Ubuntu 16.04
* automake 1.15-4ubuntu1
* autotools-dev 20150820.1

**Comment by denisdemaisbr** [comment]
@gotoo77 

try
$autoreconfig -i 
then ./configure
