### ISSUE TITLE
The README says to run ./configure but the file doesn't exists in the Github repository.

### ISSUE THREAD

**Issue by Natim** [fukuchi/libqrencode#93]
Could you tell me how to run it and also how to run the tests?

**Comment by charmander** [comment]
> When you downloaded a development tree from github, it is required to run "autogen.sh" at first to generate configure script.

In the same section of the README.

**Comment by Natim** [comment]
Sorry about that I tried with cmake and it worked.

**Comment by fukuchi** [comment]
Thank you for the report. ;)
