### ISSUE TITLE
Compile error...

### ISSUE THREAD

**Issue by M3rc3ry** [fukuchi/libqrencode#94]
Compiling in Linux Mint Sarah. Same error weather compiling directly or through the parent package.

/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:34:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_writeFormatInformation(int width, unsigned char *fra
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c: In function ‘Mask_makeMask’:
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:177:2: warning: implicit declaration of function ‘Mask_writeFormatInformation’ [-Wimplicit-function-declaration]
  Mask_writeFormatInformation(width, masked, mask, level);
  ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c: At top level:
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:188:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcN1N3(int length, int *runLength)
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:221:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcN2(int width, unsigned char *frame)
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:244:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcRunLengthH(int width, unsigned char *frame, int 
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:272:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_calcRunLengthV(int width, unsigned char *frame, int 
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:300:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 STATIC_IN_RELEASE int Mask_evaluateSymbol(int width, unsigned char *frame)
                   ^
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c: In function ‘Mask_mask’:
/home/mercury/Desktop/digitalnotewallet/libqrencode/mask.c:348:14: warning: implicit declaration of function ‘Mask_evaluateSymbol’ [-Wimplicit-function-declaration]
   demerit += Mask_evaluateSymbol(width, mask);

**Comment by fukuchi** [comment]
Please give us more info about your compiler.

**Comment by M3rc3ry** [comment]
Hello i know i am building this https://github.com/xdn-project/digitalnotewallet and it references your pakage but i can not hail an answer from them and i thought who better than ask that the master who built the qr library. this morning i managed to build it by going >sudo ./autogen.sh >sudo ./configure >mkdir build && cd build > sudo cmake .. > sudo build

last night i managed to recreate the problem using some combination. I will continue to try

GNU Make 4.1
Built for x86_64-pc-linux-gnu

**Comment by M3rc3ry** [comment]
Hi thanks. I managed to solve it. For others out there...The cryptonote pakage had it own OREncode.cmake file. In there the author managed to recreate issue #87. Fixed it with the following file https://github.com/xdn-project/digitalnotewallet/blob/master/QREncode.cmake

#list(APPEND my_definitions "__STATIC=static")
list(APPEND my_definitions "STATIC_IN_RELEASE=")

**Comment by fukuchi** [comment]
Thank you @M3rc3ry , greate report.
