### ISSUE TITLE
code for master branch not compiling

### ISSUE THREAD

**Issue by debrahul86** [fukuchi/libqrencode#97]
I have downloaded the qrencode code pointing to master branch. as per the readme, I am trying to compile the code. I am working on windows 8 and so have downloaded cygwin. while trying to run the ./configure.ac I am getting errors as 

./configure.ac: line 1: syntax error near unexpected token `[__MAJOR_VERSION],'
./configure.ac: line 1: `m4_define([__MAJOR_VERSION], [3])dnl'

What is it that I am doing wrong. Any feedback welcome.

**Comment by fukuchi** [comment]
Please run "./autogen.sh", then run "./configure", not "./configure.ac".
