### ISSUE TITLE
configure.ac:85: warning: macro 'AM_PATH_SDL' not found in library

### ISSUE THREAD

**Issue by namowen** [fukuchi/libqrencode#99]
Just for information, if someone else has the problem:
libqrencode 3.4.4 (branch 3.4)
ubuntu 16.04 lts

autogen.sh produces error
configure.ac:85: warning: macro 'AM_PATH_SDL' not found in library

after installation of SDL with
sudo apt-get install libsdl2-2.0
sudo apt-get install libsdl2-dev
didn't help.
correcting configure.ac line 85:
replacing AM_PATH_SDL with AM_PATH_SDL2 solves the problem and autogen.sh and build runs without any problems. qr codes can be created with qrencode :-)

**Comment by fukuchi** [comment]
Thank you for your report. Our latest source tree already solved this problem. I'm preparing for version 4.0 release that deprecates 3.4 branch.
